export const REQUEST_DETALLES_PRODUCTO = "REQUEST_DETALLES_PRODUCTO";
export const DETALLES_PRODUCTO_ENCONTRADA = "DETALLES_PRODUCTO_ENCONTRADA";
export const DETALLES_PRODUCTO_NO_ENCONTRADA =
  "DETALLES_PRODUCTO_NO_ENCONTRADA";
