export const AGREGAR_ARTICULO_CARRITO = "AGREGAR_ARTICULO_CARRITO";
export const QUITAR_ARTICULO_CARRITO = "QUITAR_ARTICULO_CARRITO";
export const CARRITO_GUARDAR_DIRECCION_ENVIO =
  "CARRITO_GUARDAR_DIRECCION_ENVIO";
export const CARRITO_GUARDAR_METODO_PAGO = "CARRITO_GUARDAR_METODO_PAGO";
